apiVersion: v1
kind: PersistentVolume
metadata:
  name: homelab-pv-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"