apiVersion: v1
kind: PersistentVolume
metadata:
  name: homelab-pv-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent"