apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelab-pvc-mysql-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi