apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  template:
    metadata:
      name: gitea
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.21.3
        ports:
          - containerPort: 3000
          - containerPort: 22
        volumeMounts:
          - name: data
            mountPath: /data
            subPath: gitea-data
          - name: etc-timezone-ro
            mountPath: /etc/timezone:ro
            subPath: gitea-etc-timezone-ro
          - name: etc-localtime
            mountPath: /etc/localtime:ro
            subPath: gitea-etc-localtime
        env:
          - name: USER_UID
            value: "1000"
          - name: USER_GID
            value: "1000"
          - name: GITEA__database__DB_TYPE
            value: mysql
          - name: GITEA__database__HOST
            value: mysql:3306
          - name: GITEA__database__NAME
            value: gitea
          - name: GITEA__database__USER
            value: root
          - name: GITEA__database__PASSWD
            value: root
      volumes:
        - name: data
          hostPath:
            path: /mnt/persistent/gitea
        - name: etc-timezone-ro
          hostPath:
            path: /mnt/persistent/gitea
        - name: etc-localtime
          hostPath:
            path: /mnt/persistent/gitea
  replicas: 1
  selector:
    matchLabels:
      app: gitea
    
---

apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
    - name: tcp-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
    - name: tcp-22
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022