version: "3"

networks:
  homelab:

services:
  server:
    image: gitea/gitea:1.21.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=root
    # restart: always
    networks:
      - homelab
    volumes:
      - ./gitea/gitea:/data
      - ../gitea/timezone:/etc/timezone:ro
      - ./gitea/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"