version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    privileged: true
    environment:
      - name=test
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - /opt/jenkins:/var/jenkins_home #require to add permission to the map folder
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker #require to run docker socket inside jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

  #for docker agent comment if not needed
  remote_host:
    container_name: remote-host
    image: remote-host
    build: 
      context: centos7
    networks:
      - homelab

  # For testing purposes not required can be comment during build
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - homelab:/var/lib/mysql
    networks:
      - homelab

networks:
  homelab:
    external: true
    
volumes:
  homelab:
    external: true
