version: "3.7"

networks:
  homelab:
    external: true

services:
  jenkins:
    image: jenkins:2.60.3
    container_name: jenkins
    environment:
      - name=test
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - /mnt/persistent/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  homelab:
    external: true