version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
        - homelab:/data
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab
    restart: unless-stopped
volumes:
  homelab:
    external: true
networks:
  homelab:
    external: true