version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8888
    volumes:
      - ./data:/config
      - ./data:/downloads
    ports:
      - 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped