version: '2'
services:
  dns:
    restart: always
    image: joweisberg/dnsmasq
    platform: linux/arm64
    volumes:
      - /home/cftiangco/configs/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      homelab-net:
        ipv4_address: 192.168.100.2

networks:
  homelab-net:
    external: true
