version: '3.8'

services:
  mongo:
    image: mongo:4.4 # Use the latest stable MongoDB version; 4.4 version is for Arch linux
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - homelab
  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - homelab

volumes:
  mongo_data:

networks:
  homelab:
    driver: bridge
